### ISSUE TITLE
Include epitope prediction on peptides using Fred3 

### ISSUE THREAD

**Issue by skrakau** [qbic-pipelines/metapep#13]
Include epitope prediction on peptides using Fred3 

- [x] split peptides in chunks
- [x] call epitopeprediction with Fred
- [x]  merge results and reports

**Comment by skrakau** [comment]
Maybe we can start for now by first using Fred2 and just copy stuff, and do the conversion to Fred3 later? 

Edit: not much changed in Fred3, can be probably used directly.

**Comment by lkuchenb** [comment]
Fixed in #19
